# Generated by Django 6.0.6 on 2026-06-20 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code for this hierarchy node.', max_length=80, validators=[django.core.validators.RegexValidator(message='Code must start with a letter or number and contain only letters, numbers, underscores, hyphens, or dots.', regex='^[A-Za-z0-9][A-Za-z0-9_.-]*$')])),
                ('name', models.CharField(max_length=150)),
                ('node_type', models.CharField(choices=[('company', 'Company'), ('site', 'Site'), ('facility', 'Facility / Building / Hangar'), ('area', 'Area / Process'), ('location', 'Location')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetlocationnode')),
            ],
            options={
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique asset code inside the client database.', max_length=80, validators=[django.core.validators.RegexValidator(message='Code must start with a letter or number and contain only letters, numbers, underscores, hyphens, or dots.', regex='^[A-Za-z0-9][A-Za-z0-9_.-]*$')])),
                ('name', models.CharField(max_length=180)),
                ('asset_type', models.CharField(choices=[('equipment', 'Equipment'), ('infrastructure', 'Infrastructure'), ('tooling', 'Tooling'), ('vehicle', 'Vehicle'), ('system', 'System'), ('other', 'Other')], default='equipment', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_maintenance', 'In maintenance'), ('out_of_service', 'Out of service'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=30)),
                ('criticality', models.CharField(choices=[('not_assessed', 'Not assessed'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='not_assessed', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='Flexible technical data for the asset.')),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_maintainable', models.BooleanField(default=True, help_text='Defines whether the asset can receive maintenance orders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_asset', models.ForeignKey(blank=True, help_text='Optional parent asset for future component hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_assets', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetlocationnode')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('manual', 'Manual'), ('datasheet', 'Datasheet'), ('diagram', 'Diagram'), ('procedure', 'Procedure'), ('nameplate', 'Nameplate'), ('warranty', 'Warranty'), ('invoice', 'Invoice'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('document_uri', models.CharField(blank=True, help_text='File path, URL, or storage reference for the document.', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__code', 'document_type', 'title'],
                'indexes': [models.Index(fields=['asset'], name='assets_asse_asset_i_406b48_idx'), models.Index(fields=['document_type'], name='assets_asse_documen_c47057_idx'), models.Index(fields=['deleted_at'], name='assets_asse_deleted_6e2f77_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetlocationnode',
            index=models.Index(fields=['code'], name='assets_asse_code_48d02a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationnode',
            index=models.Index(fields=['node_type'], name='assets_asse_node_ty_26c717_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationnode',
            index=models.Index(fields=['parent'], name='assets_asse_parent__eba2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationnode',
            index=models.Index(fields=['is_active'], name='assets_asse_is_acti_bc2205_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationnode',
            index=models.Index(fields=['deleted_at'], name='assets_asse_deleted_51bc67_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetlocationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_asset_location_code'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='assets_asse_code_97d73a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['criticality'], name='assets_asse_critica_a56ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location'], name='assets_asse_locatio_8c1d63_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['parent_asset'], name='assets_asse_parent__c47d76_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['deleted_at'], name='assets_asse_deleted_92ab9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_asset_code'),
        ),
    ]
