# Generated by Django 6.0.6 on 2026-06-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('subsystem', 'Subsistema'), ('component', 'Componente'), ('maintainable_point', 'Punto mantenible')], max_length=40)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_maintainable', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_nodes', to='assets.asset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetstructurenode')),
            ],
            options={
                'ordering': ['asset__code', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'code'), name='unique_active_asset_structure_code_per_asset')],
            },
        ),
    ]
