# Generated by Django 6.0.6 on 2026-06-21 00:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Code must start with a letter or number and may contain letters, numbers, dots, underscores, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('name', models.CharField(max_length=180)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('area_stock', 'Area stock'), ('technician_kit', 'Technician kit'), ('supplier', 'Supplier'), ('other', 'Other')], default='warehouse', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Code must start with a letter or number and may contain letters, numbers, dots, underscores, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.sparepartcategory')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Internal spare part code.', max_length=80, validators=[django.core.validators.RegexValidator(message='Code must start with a letter or number and may contain letters, numbers, dots, underscores, or hyphens.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('obsolete', 'Obsolete')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=120)),
                ('unit_of_measure', models.CharField(default='unit', max_length=30)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='inventory.sparepartcategory')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SparePartStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('average_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.inventorylocation')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.sparepart')),
            ],
            options={
                'ordering': ['spare_part__code', 'location__code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('initial_balance', 'Initial balance'), ('receipt', 'Receipt'), ('issue', 'Issue'), ('return', 'Return'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out')], max_length=30)),
                ('reason', models.CharField(choices=[('initial_load', 'Initial load'), ('purchase', 'Purchase'), ('maintenance_use', 'Maintenance use'), ('return_from_maintenance', 'Return from maintenance'), ('physical_count', 'Physical count'), ('damage', 'Damage'), ('loss', 'Loss'), ('correction', 'Correction'), ('other', 'Other')], default='other', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Purchase order, adjustment reference, or external document.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('movement_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.sparepartstock')),
            ],
            options={
                'ordering': ['-movement_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['code'], name='inventory_i_code_ed21e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['name'], name='inventory_i_name_39459a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['location_type'], name='inventory_i_locatio_b92b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_69b6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['deleted_at'], name='inventory_i_deleted_4d74f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_inventory_location_code'),
        ),
        migrations.AddIndex(
            model_name='sparepartcategory',
            index=models.Index(fields=['code'], name='inventory_s_code_8701d6_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartcategory',
            index=models.Index(fields=['name'], name='inventory_s_name_173a87_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartcategory',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_1537ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartcategory',
            index=models.Index(fields=['deleted_at'], name='inventory_s_deleted_1a76f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepartcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_spare_part_category_code'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['code'], name='inventory_s_code_8ad0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['name'], name='inventory_s_name_2bbe2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['status'], name='inventory_s_status_90dff0_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category'], name='inventory_s_categor_2df05f_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['deleted_at'], name='inventory_s_deleted_770b05_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_spare_part_code'),
        ),
        migrations.AddIndex(
            model_name='sparepartstock',
            index=models.Index(fields=['spare_part'], name='inventory_s_spare_p_455249_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartstock',
            index=models.Index(fields=['location'], name='inventory_s_locatio_56e182_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartstock',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_s_quantit_58e7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartstock',
            index=models.Index(fields=['deleted_at'], name='inventory_s_deleted_5e2a9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepartstock',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('spare_part', 'location'), name='unique_active_spare_part_stock_location'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item'], name='inventory_s_stock_i_bd6c56_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reason'], name='inventory_s_reason_03e330_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_at'], name='inventory_s_movemen_e9a903_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_by_user_id'], name='inventory_s_created_a92fcb_idx'),
        ),
    ]
