# Generated by Django 6.0.6 on 2026-06-20 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(help_text='Human-readable request number.', max_length=40, unique=True)),
                ('title', models.CharField(help_text='Short description of the reported issue.', max_length=180)),
                ('description', models.TextField(help_text='Detailed failure description provided by the requester.')),
                ('perceived_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('safety', 'Safety')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('received', 'Received'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('converted_to_work_order', 'Converted to work order')], default='created', max_length=40)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('admin', 'Admin'), ('import', 'Import'), ('other', 'Other')], default='web', max_length=20)),
                ('requester_user_id', models.PositiveBigIntegerField(blank=True, help_text='ID of the user in the control database. Not a FK because operational data lives in the client database.', null=True)),
                ('requester_name', models.CharField(help_text='Requester name snapshot at creation time.', max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('is_confirmed_by_requester', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_was_stopped', models.BooleanField(default=False, help_text='Indicates whether the asset was stopped when the request was created.')),
                ('safety_risk', models.BooleanField(default=False)),
                ('production_impact', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True, help_text='Optional reason for rejection, cancellation, or status change.')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Flexible data captured from form, voice transcription, or import.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_number'], name='maintenance_request_b8ff36_idx'), models.Index(fields=['asset'], name='maintenance_asset_i_7a9bf2_idx'), models.Index(fields=['status'], name='maintenance_status_13e6de_idx'), models.Index(fields=['perceived_priority'], name='maintenance_perceiv_bce1aa_idx'), models.Index(fields=['created_at'], name='maintenance_created_dca16f_idx'), models.Index(fields=['deleted_at'], name='maintenance_deleted_be80ac_idx')],
            },
        ),
    ]
