# Generated by Django 6.0.6 on 2026-06-20 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('maintenance_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_number', models.CharField(help_text='Human-readable work order number.', max_length=40, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('maintenance_request', 'Maintenance request'), ('preventive_plan', 'Preventive plan'), ('other', 'Other')], default='manual', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('work_order_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive'), ('inspection', 'Inspection'), ('improvement', 'Improvement'), ('other', 'Other')], default='corrective', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('safety', 'Safety')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('technically_closed', 'Technically closed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='created', max_length=30)),
                ('requester_user_id', models.PositiveBigIntegerField(blank=True, help_text='Requester user ID from control database snapshot.', null=True)),
                ('requester_name', models.CharField(blank=True, max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('on_hold_at', models.DateTimeField(blank=True, null=True)),
                ('technically_closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset')),
                ('source_request', models.OneToOneField(blank=True, help_text='Maintenance request that originated this work order, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='maintenance_requests.maintenancerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technician_user_id', models.PositiveBigIntegerField(help_text='Technician user ID from control database.')),
                ('technician_name', models.CharField(max_length=150)),
                ('technician_email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField()),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-is_primary', 'technician_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLaborEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technician_user_id', models.PositiveBigIntegerField()),
                ('technician_name', models.CharField(max_length=150)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTechnicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('work_performed', models.TextField()),
                ('probable_cause', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('evidence_uri', models.CharField(blank=True, help_text='File path, URL, or storage reference for evidence.', max_length=500)),
                ('closed_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('closed_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_report', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['work_order_number'], name='work_orders_work_or_e12602_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset'], name='work_orders_asset_i_4bea0e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['source'], name='work_orders_source_eb47d5_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='work_orders_status_c63f41_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='work_orders_priorit_545f15_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['work_order_type'], name='work_orders_work_or_5068ba_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['created_at'], name='work_orders_created_5c5e92_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['deleted_at'], name='work_orders_deleted_c7bbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignee',
            index=models.Index(fields=['work_order'], name='work_orders_work_or_bf3def_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignee',
            index=models.Index(fields=['technician_user_id'], name='work_orders_technic_706189_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignee',
            index=models.Index(fields=['is_active'], name='work_orders_is_acti_c866cf_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignee',
            index=models.Index(fields=['unassigned_at'], name='work_orders_unassig_122595_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderassignee',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('work_order', 'technician_user_id'), name='unique_active_work_order_assignee'),
        ),
        migrations.AddIndex(
            model_name='workorderlaborentry',
            index=models.Index(fields=['work_order'], name='work_orders_work_or_a44ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderlaborentry',
            index=models.Index(fields=['technician_user_id'], name='work_orders_technic_929aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderlaborentry',
            index=models.Index(fields=['started_at'], name='work_orders_started_cba6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertechnicalreport',
            index=models.Index(fields=['work_order'], name='work_orders_work_or_a3ef05_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertechnicalreport',
            index=models.Index(fields=['closed_by_user_id'], name='work_orders_closed__5a62df_idx'),
        ),
    ]
