# Generated by Django 6.0.6 on 2026-06-18 05:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Short unique code used internally to identify the tenant.', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Commercial name of the tenant.', max_length=150)),
                ('legal_name', models.CharField(blank=True, help_text='Legal name or registered company name.', max_length=200)),
                ('tax_id', models.CharField(blank=True, help_text='Optional tax identification number.', max_length=50)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='provisioning', max_length=20)),
                ('database_name', models.CharField(help_text='Dedicated operational database assigned to this tenant.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Database name must start with a lowercase letter and contain only lowercase letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('database_host', models.CharField(default='localhost', max_length=255)),
                ('database_port', models.PositiveIntegerField(default=5433, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='tenancy_ten_code_6a5e72_idx'), models.Index(fields=['status'], name='tenancy_ten_status_4ae576_idx'), models.Index(fields=['database_name'], name='tenancy_ten_databas_bb9553_idx')],
            },
        ),
    ]
