OPERATIONAL_PERMISSIONS = [
    # Assets
    {
        "code": "assets.view_asset_location",
        "name": "View asset locations",
        "module": "assets",
        "description": "Can view technical location hierarchy.",
    },
    {
        "code": "assets.create_asset_location",
        "name": "Create asset locations",
        "module": "assets",
        "description": "Can create technical location hierarchy nodes.",
    },
    {
        "code": "assets.view_asset",
        "name": "View assets",
        "module": "assets",
        "description": "Can view equipment and infrastructure assets.",
    },
    {
        "code": "assets.create_asset",
        "name": "Create assets",
        "module": "assets",
        "description": "Can create equipment and infrastructure assets.",
    },
    {
        "code": "assets.view_asset_document",
        "name": "View asset documents",
        "module": "assets",
        "description": "Can view asset technical documents.",
    },
    {
        "code": "assets.create_asset_document",
        "name": "Create asset documents",
        "module": "assets",
        "description": "Can add technical documents to assets.",
    },

    # Maintenance requests
    {
        "code": "maintenance_requests.view_request",
        "name": "View maintenance requests",
        "module": "maintenance_requests",
        "description": "Can view maintenance failure reports.",
    },
    {
        "code": "maintenance_requests.create_request",
        "name": "Create maintenance requests",
        "module": "maintenance_requests",
        "description": "Can report a maintenance failure.",
    },
    {
        "code": "maintenance_requests.receive_request",
        "name": "Receive maintenance requests",
        "module": "maintenance_requests",
        "description": "Can mark a maintenance request as received.",
    },
    {
        "code": "maintenance_requests.reject_request",
        "name": "Reject maintenance requests",
        "module": "maintenance_requests",
        "description": "Can reject a maintenance request.",
    },
    {
        "code": "maintenance_requests.cancel_request",
        "name": "Cancel maintenance requests",
        "module": "maintenance_requests",
        "description": "Can cancel a maintenance request.",
    },
    {
        "code": "maintenance_requests.convert_to_work_order",
        "name": "Convert requests to work orders",
        "module": "maintenance_requests",
        "description": "Can convert a maintenance request into a work order.",
    },

    # Work orders
    {
        "code": "work_orders.view_work_order",
        "name": "View work orders",
        "module": "work_orders",
        "description": "Can view work orders.",
    },
    {
        "code": "work_orders.create_work_order",
        "name": "Create work orders",
        "module": "work_orders",
        "description": "Can create work orders manually.",
    },
    {
        "code": "work_orders.assign_technician",
        "name": "Assign technicians",
        "module": "work_orders",
        "description": "Can assign technicians to work orders.",
    },
    {
        "code": "work_orders.start_work_order",
        "name": "Start work orders",
        "module": "work_orders",
        "description": "Can start assigned work orders.",
    },
    {
        "code": "work_orders.put_on_hold",
        "name": "Put work orders on hold",
        "module": "work_orders",
        "description": "Can put work orders on hold.",
    },
    {
        "code": "work_orders.technical_close",
        "name": "Technical close work orders",
        "module": "work_orders",
        "description": "Can technically close work orders.",
    },
    {
        "code": "work_orders.final_close",
        "name": "Final close work orders",
        "module": "work_orders",
        "description": "Can perform final administrative close of work orders.",
    },
    {
        "code": "work_orders.cancel_work_order",
        "name": "Cancel work orders",
        "module": "work_orders",
        "description": "Can cancel work orders.",
    },
    {
        "code": "work_orders.add_labor_entry",
        "name": "Add labor entries",
        "module": "work_orders",
        "description": "Can register labor time against work orders.",
    },

    # Inventory
    {
        "code": "inventory.view_spare_part",
        "name": "View spare parts",
        "module": "inventory",
        "description": "Can view spare parts.",
    },
    {
        "code": "inventory.create_spare_part",
        "name": "Create spare parts",
        "module": "inventory",
        "description": "Can create spare parts.",
    },
    {
        "code": "inventory.view_inventory_location",
        "name": "View inventory locations",
        "module": "inventory",
        "description": "Can view warehouses and inventory locations.",
    },
    {
        "code": "inventory.create_inventory_location",
        "name": "Create inventory locations",
        "module": "inventory",
        "description": "Can create warehouses and inventory locations.",
    },
    {
        "code": "inventory.view_stock",
        "name": "View stock",
        "module": "inventory",
        "description": "Can view stock by spare part and location.",
    },
    {
        "code": "inventory.create_stock",
        "name": "Create stock records",
        "module": "inventory",
        "description": "Can create stock records.",
    },
    {
        "code": "inventory.view_stock_movement",
        "name": "View stock movements",
        "module": "inventory",
        "description": "Can view stock movement history.",
    },
    {
        "code": "inventory.create_stock_movement",
        "name": "Create stock movements",
        "module": "inventory",
        "description": "Can create inventory stock movements.",
    },

    # Accounts
    {
        "code": "accounts.view_user",
        "name": "View users",
        "module": "accounts",
        "description": "Can view users.",
    },
    {
        "code": "accounts.manage_user",
        "name": "Manage users",
        "module": "accounts",
        "description": "Can create and manage users.",
    },
    {
        "code": "accounts.manage_role",
        "name": "Manage roles",
        "module": "accounts",
        "description": "Can create and manage roles.",
    },
    {
        "code": "accounts.manage_permission",
        "name": "Manage permissions",
        "module": "accounts",
        "description": "Can manage operational permissions.",
    },
]


ROLE_TEMPLATES = [
    {
        "code": "system_admin",
        "name": "System administrator",
        "description": "Full operational access to the CMMS.",
        "permission_codes": [permission["code"] for permission in OPERATIONAL_PERMISSIONS],
    },
    {
        "code": "maintenance_manager",
        "name": "Maintenance manager",
        "description": "Can manage assets, requests, work orders, and inventory.",
        "permission_codes": [
            "assets.view_asset_location",
            "assets.create_asset_location",
            "assets.view_asset",
            "assets.create_asset",
            "assets.view_asset_document",
            "assets.create_asset_document",
            "maintenance_requests.view_request",
            "maintenance_requests.create_request",
            "maintenance_requests.receive_request",
            "maintenance_requests.reject_request",
            "maintenance_requests.cancel_request",
            "maintenance_requests.convert_to_work_order",
            "work_orders.view_work_order",
            "work_orders.create_work_order",
            "work_orders.assign_technician",
            "work_orders.start_work_order",
            "work_orders.put_on_hold",
            "work_orders.technical_close",
            "work_orders.final_close",
            "work_orders.cancel_work_order",
            "work_orders.add_labor_entry",
            "inventory.view_spare_part",
            "inventory.create_spare_part",
            "inventory.view_inventory_location",
            "inventory.create_inventory_location",
            "inventory.view_stock",
            "inventory.create_stock",
            "inventory.view_stock_movement",
            "inventory.create_stock_movement",
        ],
    },
    {
        "code": "maintenance_planner",
        "name": "Maintenance planner",
        "description": "Can receive requests, create work orders, and assign technicians.",
        "permission_codes": [
            "assets.view_asset_location",
            "assets.view_asset",
            "assets.view_asset_document",
            "maintenance_requests.view_request",
            "maintenance_requests.receive_request",
            "maintenance_requests.convert_to_work_order",
            "work_orders.view_work_order",
            "work_orders.create_work_order",
            "work_orders.assign_technician",
            "inventory.view_spare_part",
            "inventory.view_stock",
        ],
    },
    {
        "code": "maintenance_technician",
        "name": "Maintenance technician",
        "description": "Can view and execute assigned work orders.",
        "permission_codes": [
            "assets.view_asset",
            "assets.view_asset_document",
            "maintenance_requests.view_request",
            "work_orders.view_work_order",
            "work_orders.start_work_order",
            "work_orders.put_on_hold",
            "work_orders.technical_close",
            "work_orders.add_labor_entry",
            "inventory.view_spare_part",
            "inventory.view_stock",
        ],
    },
    {
        "code": "maintenance_requester",
        "name": "Maintenance requester",
        "description": "Can report failures and view own operational context.",
        "permission_codes": [
            "assets.view_asset",
            "maintenance_requests.view_request",
            "maintenance_requests.create_request",
        ],
    },
    {
        "code": "inventory_keeper",
        "name": "Inventory keeper",
        "description": "Can manage spare parts, stock, and inventory movements.",
        "permission_codes": [
            "inventory.view_spare_part",
            "inventory.create_spare_part",
            "inventory.view_inventory_location",
            "inventory.create_inventory_location",
            "inventory.view_stock",
            "inventory.create_stock",
            "inventory.view_stock_movement",
            "inventory.create_stock_movement",
        ],
    },
    {
        "code": "viewer",
        "name": "Viewer",
        "description": "Read-only access to operational CMMS information.",
        "permission_codes": [
            "assets.view_asset_location",
            "assets.view_asset",
            "assets.view_asset_document",
            "maintenance_requests.view_request",
            "work_orders.view_work_order",
            "inventory.view_spare_part",
            "inventory.view_inventory_location",
            "inventory.view_stock",
            "inventory.view_stock_movement",
        ],
    },
]