# Generated by Django 6.0.6 on 2026-06-19 22:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short unique role code, for example: maintenance_supervisor.', max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Marks roles created by the platform and not by a tenant admin.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal permission code, for example: work_orders.create.', max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Permission code must use lowercase segments separated by dots, for example: work_orders.create.', regex='^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$')])),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(choices=[('core', 'Core'), ('tenancy', 'Tenancy'), ('accounts', 'Accounts'), ('assets', 'Assets'), ('maintenance_requests', 'Maintenance requests'), ('work_orders', 'Work orders'), ('inventory', 'Inventory'), ('reporting', 'Reporting'), ('administration', 'Administration')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['code'], name='accounts_op_code_cfe692_idx'), models.Index(fields=['module'], name='accounts_op_module_32baaf_idx'), models.Index(fields=['is_active'], name='accounts_op_is_acti_b0abbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.operationalpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'ordering': ['role__name', 'permission__code'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermission', to='accounts.operationalpermission'),
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='TenantUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user_roles', to='accounts.role')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user_roles', to='accounts.tenantuser')),
            ],
            options={
                'ordering': ['tenant_user__tenant__name', 'role__name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_global_support', models.BooleanField(default=False, help_text='Allows the user to be marked as internal platform support.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cmms_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='accounts_ro_code_5aeee6_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='accounts_ro_is_acti_8f899c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'user'], name='accounts_te_tenant__f15c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['is_active'], name='accounts_te_is_acti_e3c8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['deleted_at'], name='accounts_te_deleted_417402_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantuser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'user'), name='unique_active_tenant_user'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuserrole',
            unique_together={('tenant_user', 'role')},
        ),
    ]
